# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 226b6b72cb728b6b936d6e95aa47423513afd70b67e76da75e752f2f896b280dfccf9e85808de18652746c0da828e79039eee82f7a9c35e2f6f70927e470a7cf

test:
  secret_key_base: fd174b9b6787669c691f455d33cbdeddeddbd5351da19d751eb7634e0e4092d61898c7e924303a034ab55e49f9b4e139c587ff1ed892f72c2b41eec40256dd88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
